{
 "title": "API_request",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Average time HTTP request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(demo_api_request_duration_seconds_sum[5m])) by (method, path) / sum(rate(demo_api_request_duration_seconds_count[5m])) by (method, path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentile 0.95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method, path) (rate(demo_api_request_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentile 0.90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, method, path, status) (rate(demo_api_request_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}